# Example pipeline config file
# Pipeline configuration for vision-pipeline-benchmarks
# Adjust model paths, source, and flush interval as needed.

source:
  type: folder                                        # 'folder' or 'rtsp'
  path: ../video_processing/test_videos      # used when type=folder
  rtsp_url: rtsp://user:pass@host/path                # used when type=rtsp
  rtsp_limit_seconds: 300
  source_id: sequential_test_run1                    # identifier written to Postgres

pipeline:

  # model one config 
  model1_path: models/yolov8m.pt           # first model - e.g., fine tuned for a specific use case
  model_name: "fine-tuned-car-model_v1"    # Allows us to track model versions
  model_type: "detection"                     
  model_mode: "detect"                     # Can pass modes like detect vs track as a parameter
  model1_confidence: 0.4
  model1_class_number: 0 
  model1_class_name: "Person"

 
  # model two config
  model2_path: models/yolov8m.pt            # second model - e.g., tracking a separate but related use case vs  model #1
  model_name: "fine-tuned-people-model_v1"  
  model_type: "detection"
  model_mode: "detect"
  model2_confidence: 0.4
  model2_class_number: 2
  model2_class_name: "Car"
  
  # general config
  flush_interval_seconds: 60            # how often to write summary to DBs


  # data saving config
  influx_db_measurement: "sequential-test1_telemetry"
  postgres_database: "vision_pipeline_benchmark_analytics"
  postgres_table: "sequential_benchmark_analytics_data"

telemetry:
  hardware_label: "NVIDIA 4060 mobile"
  pipeline_label: "async"
  site_label: "local-dev"

video_config:

  # RTSP config
  RTSP_LENGTH: 1200  # in seconds
